# Week 06 Pandas 병합과 연결 실습

이번 실습은 `DataFrame` 생성, `concat()`, `merge()`의 핵심 패턴을 차례대로 확인하는 흐름으로 구성합니다.

In [3]:
import pandas as pd

## 0. 수업 예시 형태로 DataFrame 만들기

In [14]:
raw_data = {
    'subject_id': ['1', '2', '3', '4', '5','8'],
    'test_score': [51, 15, 15, 61, 16, 10]
}

df_score = pd.DataFrame(raw_data, columns=['subject_id', 'test_score'])
df_score

  subject_id  test_score
0          1          51
1          2          15
2          3          15
3          4          61
4          5          16
5          8          10

## 1. 병합에 사용할 기본 표 만들기

In [16]:
df_left = pd.DataFrame({
    'subject_id': ['1', '2', '3', '4'],
    'first_name': ['Alex', 'Amy', 'Allen', 'Alice'],
    'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni']
})

df_right = pd.DataFrame({
    'subject_id': ['1', '2', '3', '5'],
    'test_score': [51, 15, 15, 61],
    'class_name': ['A', 'B', 'A', 'C']
})

print('df_left')
display(df_left)
print('df_right')
display(df_right)

df_left

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni

df_right

  subject_id  test_score class_name
0          1          51          A
1          2          15          B
2          3          15          A
3          5          61          C

## 2. `concat()`으로 위아래 연결

In [ ]:
df_class_a = pd.DataFrame({
    'subject_id': ['1', '2'],
    'test_score': [80, 90]
})

df_class_b = pd.DataFrame({
    'subject_id': ['3', '4'],
    'test_score': [75, 88]
})

row_concat = pd.concat([df_class_a, df_class_b], axis=0, ignore_index=True)
row_concat

## 3. `concat()`으로 좌우 연결

In [ ]:
df_name = pd.DataFrame({
    'first_name': ['Alex', 'Amy', 'Allen']
})

df_grade = pd.DataFrame({
    'test_score': [51, 15, 15]
})

col_concat = pd.concat([df_name, df_grade], axis=1)
col_concat

## 4. `merge()` 기본값: inner join

In [ ]:
inner_result = pd.merge(df_left, df_right, on='subject_id', how='inner')
inner_result

## 5. left, right, outer join 비교

In [ ]:
left_result = pd.merge(df_left, df_right, on='subject_id', how='left')
right_result = pd.merge(df_left, df_right, on='subject_id', how='right')
outer_result = pd.merge(df_left, df_right, on='subject_id', how='outer')

print('left join')
display(left_result)
print('right join')
display(right_result)
print('outer join')
display(outer_result)

## 6. 기준 열 이름이 다를 때

In [ ]:
df_attendance = pd.DataFrame({
    'id': ['1', '2', '4'],
    'attendance': ['Y', 'N', 'Y']
})

merge_with_different_keys = pd.merge(
    df_left,
    df_attendance,
    left_on='subject_id',
    right_on='id',
    how='left'
)
merge_with_different_keys

## 7. 같은 이름의 점수 열이 겹칠 때

In [18]:
midterm = pd.DataFrame({
    'subject_id': ['1', '2', '3'],
    'test_score': [80, 90, 70]
})

final = pd.DataFrame({
    'subject_id': ['1', '2', '3'],
    'test_score': [85, 95, 75]
})

score_compare = pd.merge(midterm, final, on='subject_id', suffixes=('_mid', '_final'))
score_compare

  subject_id  test_score_mid  test_score_final
0          1              80                85
1          2              90                95
2          3              70                75

## 8. `indicator=True`로 출처 확인하기

In [ ]:
checked_merge = pd.merge(
    df_left,
    df_right,
    on='subject_id',
    how='outer',
    indicator=True
)
checked_merge

## 9. 중복 키가 있으면 행 수가 늘어날 수 있음

In [ ]:
df_dup = pd.DataFrame({
    'subject_id': ['1', '1', '2'],
    'quiz_score': [10, 20, 30]
})

dup_merge = pd.merge(df_left, df_dup, on='subject_id', how='inner')
dup_merge

## 10. 실습 체크 포인트

- `concat()`은 단순 연결이고, `merge()`는 키 기준 결합이다.
- `how='left'`는 왼쪽 표를 기준으로 유지한다.
- 열 이름이 다르면 `left_on`, `right_on`을 쓴다.
- 같은 이름의 일반 열이 겹치면 `suffixes`로 구분한다.
- 병합 후 `NaN`이 생기면 매칭되지 않은 키가 있는지 먼저 본다.